export const voices = [
  { value: 'Ivy', label: 'Ivy [English - American]', lang: 'English' },
  { value: 'Joanna', label: 'Joanna [English - American]', lang: 'English' },
  { value: 'Joey', label: 'Joey [English - American]', lang: 'English' },
  { value: 'Justin', label: 'Justin [English - American]', lang: 'English' },
  { value: 'Kendra', label: 'Kendra [English - American]', lang: 'English' },
  { value: 'Kimberly', label: 'Kimberly [English - American]', lang: 'English' },
  { value: 'Salli', label: 'Salli [English - American]', lang: 'English' },
  { value: 'Nicole', label: 'Nicole [English - Australian]', lang: 'English' },
  { value: 'Russell', label: 'Russell [English - Australian]', lang: 'English' },
  { value: 'Emma', label: 'Emma [English - British]', lang: 'English' },
  { value: 'Brian', label: 'Brian [English - British]', lang: 'English' },
  { value: 'Amy', label: 'Amy [English - British]' },
  { value: 'Raveena', label: 'Raveena [English - Indian]', lang: 'English' },
  { value: 'Geraint', label: 'Geraint [English - Welsh]', lang: 'English' },
  { value: 'Ricardo', label: 'Ricardo [Brazilian Portuguese]', lang: 'Portuguese' },
  { value: 'Vitoria', label: 'Vitoria [Brazilian Portuguese]', lang: 'Portuguese' },
  { value: 'Cristiano', label: 'Cristiano [Portuquese]', lang: 'Portuguese' },
  { value: 'Ines', label: 'Ines [Portuquese]', lang: 'Portuguese' },
  { value: 'Lotte', label: 'Lotte [Dutch]', lang: 'Dutch' },
  { value: 'Ruben', label: 'Ruben [Dutch]', lang: 'Dutch' },
  { value: 'Mathieu', label: 'Mathieu [French]', lang: 'French' },
  { value: 'Celine', label: 'Celine [French]', lang: 'French' },
  { value: 'Chantal', label: 'Chantal [Canadian French]', lang: 'French' },
  { value: 'Marlene', label: 'Marlene [German]', lang: 'German' },
  { value: 'Dora', label: 'Dora [Icelandic]', lang: 'Icelandic' },
  { value: 'Karl', label: 'Karl [Icelandic]', lang: 'Icelandic' },
  { value: 'Carla', label: 'Carla [Italian]', lang: 'Italian' },
  { value: 'Giorgio', label: 'Giorgio [Italian]', lang: 'Italian' },
  { value: 'Mizuki', label: 'Mizuki [Japanese]', lang: 'Japanese' },
  { value: 'Liv', label: 'Liv [Norwegian]', lang: 'Norwegian' },
  { value: 'Maja', label: 'Maja [Polish]', lang: 'Polish' },
  { value: 'Jan', label: 'Jan [Polish]', lang: 'Polish' },
  { value: 'Ewa', label: 'Ewa [Polish]', lang: 'Polish' },
  { value: 'Carmen', label: 'Carmen [Romanian]', lang: 'Romanian' },
  { value: 'Maxim', label: 'Maxim [Russian]', lang: 'Russian' },
  { value: 'Tatyana', label: 'Tatyana [Russian]', lang: 'Russian' },
  { value: 'Enrique', label: 'Enrique [Spanish]', lang: 'Spanish' },
  { value: 'Penelope', label: 'Penelope [US Spanish]', lang: 'Spanish' },
  { value: 'Conchita', label: 'Conchita [Castilian Spanish]', lang: 'Spanish' },
  { value: 'Astrid', label: 'Astrid [Swedish]', lang: 'Swedish' },
  { value: 'Filiz', label: 'Filiz [Turkish]', lang: 'Turkish' },
  { value: 'Gwyneth', label: 'Gwyneth [Welsh]', lang: 'Welsh' }
]
